//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { IIngredientDTO } from './IIngredientDTO';

export interface IRecipeDTO
{
	RecipeId: any;
	Title: string;
	WorkingTime?: number;
	PreparationTime?: number;
	Ingredients: IIngredientDTO[];
}
