//     This code was generated by a Reinforced.Typings tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { IUserDTO } from './IUserDTO';

export interface IUserLoginResponseDTO
{
	jwtToken: string;
	userDTO?: IUserDTO;
	message: string;
}
